---
roles:
    - name: geerlingguy.security
    - name: geerlingguy.docker
    - name: geerlingguy.ntp
    - name: geerlingguy.pip
    - name: geerlingguy.firewall

collections:
    - name: community.docker
