---
services:
  gluetun:
      container_name: gluetun
      image: qmcgaw/gluetun
      cap_add:
        - NET_ADMIN
      environment:
        - VPNSP=mullvad
        - VPN_TYPE=wireguard
        - WIREGUARD_PRIVATE_KEY={{ wg_private_key }}
        - WIREGUARD_ADDRESSES={{ wg_addresses }}
        - SERVER_COUNTRIES={{ wg_countries }}
        - TZ={{ timezone }}
      volumes:
        - "{{ docker_dir }}/gluetun:/gluetun"
      restart: always

  qbittorrent:
      container_name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent
      network_mode: "service:gluetun"
      environment:
        - PUID=1000
        - PGID=1001
        - TZ={{ timezone }}
        - WEBUI_PORT=8085
      volumes:
        - "{{ docker_dir }}/qbittorrent/config:/config"
        - "{{ storage_dir }}/torrent/downloads:/downloads"
      restart: always

  nginxproxymanager:
      container_name: nginxproxymanager
      image: jc21/nginx-proxy-manager:latest
      ports:
        - '0.0.0.0:80:80'
        - '81:81'
        - '0.0.0.0:443:443'
      volumes:
        - "{{ docker_dir }}/nginxproxymanager/data:/data"
        - "{{ docker_dir }}/nginxproxymanager/letsencrypt:/etc/letsencrypt"
      restart: unless-stopped

#  pihole:
#    container_name: pihole
#    image: cbcrowe/pihole-unbound:latest
#    networks:
#      app:
#        ipv4_address: {{ networks.app.base }}.10
#    #hostname: ${HOSTNAME}
#    #domainname: ${DOMAIN_NAME}
#    ports:
#      #- 443:443/tcp
#      - 53:53/tcp
#      - 53:53/udp
#    environment:
#      - TZ={{ timezone }}
#      - WEBPASSWORD=blah123@
#      - WEBTHEME=default-dark
#      - REV_SERVER=true
#      - REV_SERVER_TARGET={{ ansible_default_ipv4.gateway }}
#      - REV_SERVER_DOMAIN=box
#      - REV_SERVER_CIDR={{ networks.app.cidr }}
#      - DNS1=127.0.0.1#5335
#      - DNS2=127.0.0.1#5335
#      - DNSSEC=true
#      - DNSMASQ_LISTENING=single
#      - DNS_NAME:pihole.box
#    volumes:
#      - "{{ docker_dir }}/pihole/pihole:/etc/pihole"
#      - "{{ docker_dir }}/pihole/dnmasq-unbound:/etc/dnsmasq.d"
#      - "{{ docker_dir }}/pihole/unbound.conf.d/pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf"
#    restart: always
