#
# Misc
#
hostname: '{{ inventory_hostname }}'

timezone: America/Sao_Paulo

ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

keyboard_layout: us

username: victor

ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINf+Mb/HfChOnFz7UtcQzcYBUrrrCWjWeljPB5fAdGoP"

password: "{{ linux_pwd }}"

shell: /usr/bin/fish

docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

storage_dir: /media

dotfiles_repo: https://github.com/notthebee/dotfiles

networks:
  lan:
    cidr: 192.168.0.0/24
    base: 192.168.0
    interface: enp1s0
  app:
    cidr: 10.0.0.0/24
    base: 10.0.0

#
# Packages
#
extra_packages:
    - fish
    - iperf3
    - speedtest-cli
    - htop
    - stow
    - exa
    - git
    - neofetch
    - neovim
    - tmux
    - mosh
    - rsync
    - lm-sensors
    - iotop
    - ncdu

#
# Email credentials (for notifications)
#

#email: moe@notthebe.ee
#
#email_login: '{{ email }}'
#
#email_smtp_host: smtp.mailbox.org
#
#email_smtp_port: 465
#
#email_smtp_port_startls: 587

# MSMTP
msmtp_accounts:
    - account: mailbox
      host: '{{ email_smtp_host }}'
      port: '{{ email_smtp_port_startls }}'
      auth: 'on'
      from: '{{ email }}'
      user: '{{ email }}'
      password: '{{ email_password }}'

msmtp_default_account: 'mailbox'

msmtp_alias_default: '{{ email }}'

#
# SSH (geerlingguy.security)
#
security_ssh_port: 69

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

#security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false

#update_utility: dnf-automatic
#
#update_service: dnf-automatic-install.timer
#
#update_conf_path: /etc/dnf/automatic.conf
#

#VPN
wg_addresses: "10.66.210.171/32"
wg_countries: "Brazil"
