#
# Misc
#
hostname: '{{ inventory_hostname }}'

timezone: America/Toronto

ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

keyboard_layout: us

username: vic

ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINf+Mb/HfChOnFz7UtcQzcYBUrrrCWjWeljPB5fAdGoP"

password: "{{ linux_pwd }}"

shell: /usr/bin/bash

# geerlingguy.pip
pip_install_packages:
  - name:
    - docker
    - docker-compose

# geerlingguy.firewall
firewall_allowed_tcp_ports:
  - "80"
  - "81"
  - "443"
  - "{{ security_ssh_port }}"
firewall_flush_rules_and_chains: false

docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

storage_dir: /media

#dotfiles_repo:

networks:
  lan:
    cidr: 192.168.0.0/24
    base: 192.168.0
    interface: enp1s0
#  app:
#    cidr: 10.20.0.0/24
#    base: 10.20.0
#    interface: enp1s0
  app:
    cidr: 10.88.111.0/24
    base: 10.88.111
    interface: enp1s0

#
# Packages
#
extra_packages:
    - iperf3
    - speedtest-cli
    - htop
    - stow
    - exa
    - git
    - neofetch
    - neovim
    - tmux
    - mosh
    - rsync
    - lm-sensors
    - iotop
    - ncdu
    - tree
    - cron
    - net-tools

#
# SSH (geerlingguy.security)
#
security_ssh_port: 69

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

#security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false

#VPN
wg_addresses: "10.66.210.171/32"
wg_countries: "Canada"
