---
- name: Chown the repo
  file:
      path: '/home/{{ username }}/dotfiles'
      recurse: yes
      state: directory
      owner: '{{ username }}'
      group: '{{ username }}'

- name: Clone the latest dotfiles repo
  become_user: '{{ username }}'
  git:
      repo: '{{ dotfiles_repo }}'
      dest: '/home/{{ username }}/dotfiles'
      recursive: no
      force: yes

- name: Stow the dotfiles
  become_user: '{{ username }}'
  shell:
      cmd: stow -v */
      chdir: '/home/{{ username }}/dotfiles'
  register: stow_result
  changed_when: stow_result.stdout != ""
