---
- name: Template out the netplan file
  ansible.builtin.template:
    src: netplan.yml
    dest: /etc/netplan/00-ansible.yml
    owner: root
    group: root
    mode: 0644
  notify: Apply netplan config

- meta: flush_handlers
