---
#- name: Ensure dependencies are present
#  apt:
#    name:
#      - apt-transport-https
#      - software-properties-common
#      - python3-pip
#      - virtualenv
#      - python3-setuptools
#    state: present
#
#- name: Install docker module for Python
#  pip:
#    name:
#      - docker
#    #extra_args: --break-system-packages

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- include_tasks: network.yml

- include_tasks: media.yml
