---
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}/media"

- name: Copy the compose file
  template:
    src: templates/compose-media.yml
    dest: "{{ docker_compose_dir }}/media/media.yml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/media"
    files: "media.yml"
